/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventasdao.ui.abm;

import com.sun.security.ntlm.Client;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import ventasdao.controladores.ClienteControlador;
import ventasdao.controladores.TipoClienteControlador;
import ventasdao.objetos.Cliente;
import ventasdao.objetos.TipoCliente;
import ventasdao.ui.grilla.GrillaCliente;

/**
 *
 * @author Gaston
 */
public class AbmCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form AbmCliente
     */
    
    private GrillaCliente grillaCliente;
    private ClienteControlador clienteControlador;
    private TipoClienteControlador tipoClienteControlador;
    private DefaultComboBoxModel modelCombo;
    
    
    public AbmCliente() {
        initComponents();
        
        clienteControlador = new ClienteControlador();
        tipoClienteControlador = new TipoClienteControlador();
        
        try {
            grillaCliente = new GrillaCliente(clienteControlador.listar());
            jtListadoCliente.setModel(grillaCliente);
        } catch (Exception ex) {
            Logger.getLogger(AbmProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
                    
        try {
            ArrayList<TipoCliente> tipoCliente = (ArrayList<TipoCliente>) tipoClienteControlador.listar();
            
            modelCombo = new DefaultComboBoxModel(tipoCliente.toArray());
            jcbTipoCliente.setModel(modelCombo);
        } catch (Exception ex) {
            Logger.getLogger(AbmProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        /*
        ArrayList<Cliente> clientes;
        try {
            clientes = clienteControlador.listar();
            grillaCliente = new GrillaCliente(clientes);
        } catch (Exception e) {
            e.printStackTrace ();
        }
        
        jtListadoCliente.setModel(grillaCliente);
        
        try {
            modelCombo = new DefaultComboBoxModel(tipoClienteControlador.listar().toArray());
        } catch (Exception ex) {
            Logger.getLogger(AbmCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        jcbTipoCliente.setModel(modelCombo);*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfNombre = new javax.swing.JTextField();
        jtfCuil = new javax.swing.JTextField();
        jtfRazonSocial = new javax.swing.JTextField();
        jlNombre = new javax.swing.JLabel();
        jlCuil = new javax.swing.JLabel();
        jlRazonSociial = new javax.swing.JLabel();
        jbAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListadoCliente = new javax.swing.JTable();
        jbModificar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jlTipoCliente = new javax.swing.JLabel();
        jtfId = new javax.swing.JTextField();
        jlId = new javax.swing.JLabel();
        jcbTipoCliente = new javax.swing.JComboBox<>();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Clientes");

        jlNombre.setText("Nombre");

        jlCuil.setText("Cuil");

        jlRazonSociial.setText("Razon Social");

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        jtListadoCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtListadoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtListadoClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtListadoCliente);

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jlTipoCliente.setText("Tipo Cliente");

        jtfId.setEnabled(false);

        jlId.setText("ID");

        jcbTipoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Tipo" }));
        jcbTipoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNombre)
                    .addComponent(jlCuil)
                    .addComponent(jlRazonSociial)
                    .addComponent(jlTipoCliente)
                    .addComponent(jlId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfCuil, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfRazonSocial, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbTipoCliente, javax.swing.GroupLayout.Alignment.LEADING, 0, 196, Short.MAX_VALUE)
                    .addComponent(jtfId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jbAgregar)
                .addGap(18, 18, 18)
                .addComponent(jbModificar)
                .addGap(18, 18, 18)
                .addComponent(jbEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCuil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCuil))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlRazonSociial))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlTipoCliente))
                        .addGap(0, 131, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregar)
                    .addComponent(jbModificar)
                    .addComponent(jbEliminar))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        // TODO add your handling code here:
        Cliente cliente = new Cliente();
        
        cliente.setNombre(jtfNombre.getText());
        cliente.setCuil(jtfCuil.getText());
        cliente.setRazonSocial(jtfRazonSocial.getText());
        cliente.setTipoCliente((TipoCliente)jcbTipoCliente.getSelectedItem());
        
        try 
        {
            clienteControlador.crear(cliente);
        } catch (Exception ex) {
            Logger.getLogger(AbmCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        try 
        {
            jtListadoCliente.setModel(new GrillaCliente(clienteControlador.listar()));
        } 
        catch (Exception ex) {
            Logger.getLogger(AbmCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.resetFields();
        this.refreshTable();
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jtListadoClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListadoClienteMouseClicked
        // TODO add your handling code here:
        Cliente cliente = grillaCliente.getClienteFromRow(jtListadoCliente.getSelectedRow());
        jtfId.setText(cliente.getId().toString());
        jtfNombre.setText(cliente.getNombre());
        jtfCuil.setText(cliente.getCuil());
        jtfRazonSocial.setText(cliente.getRazonSocial());
        jcbTipoCliente.setSelectedItem(cliente.getTipoCliente());
    }//GEN-LAST:event_jtListadoClienteMouseClicked

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        Cliente cliente = new Cliente();
        
        cliente.setId(Integer.parseInt(jtfId.getText()));
        
        try {
            clienteControlador.eliminar(cliente);
        } catch (Exception ex) {
            Logger.getLogger(AbmCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            jtListadoCliente.setModel(new GrillaCliente(clienteControlador.listar()));
        } catch (Exception ex) {
            Logger.getLogger(AbmCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.resetFields();
        this.refreshTable();
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        // TODO add your handling code here:
        Cliente cliente = new Cliente();
        
        cliente.setNombre(jtfNombre.getText());
        cliente.setCuil(jtfCuil.getText());
        cliente.setRazonSocial(jtfRazonSocial.getText());
        cliente.setId(Integer.parseInt(jtfId.getText()));
        cliente.setTipoCliente((TipoCliente) jcbTipoCliente.getSelectedItem());
        
        try {
            clienteControlador.modificar(cliente);
        } catch (Exception ex) {
            Logger.getLogger(AbmCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            jtListadoCliente.setModel(new GrillaCliente(clienteControlador.listar()));
        } catch (Exception ex) {
            Logger.getLogger(AbmCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.resetFields();
        this.refreshTable();
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jcbTipoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoClienteActionPerformed
        // TODO add your handling code here:
        /*
        cliente=new Cliente();
        
        TipoClienteControlador tipoClienteControl = new TipoClienteControlador();
        ArrayList<TipoCliente> alTipo = new ArrayList<>();
        
        try {
            alTipo = (ArrayList<TipoCliente>) tipoClienteControl.listar();
        } catch (Exception ex) {
            Logger.getLogger(AbmCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        TipoCliente[] obj= new TipoCliente[alTipo.size()];
        for (int i = 0; i < alTipo.size(); i++) {
            obj[i]= alTipo.get(i);
          
        }
        DefaultComboBoxModel<TipoCliente> boxModel= new DefaultComboBoxModel<>(obj);
        //jcbTipoCliente.setModel(boxModel);
        jcbTipoCliente.setSelectedItem(null);
        this.resetFields();
        this.refreshTable();
*/
    }//GEN-LAST:event_jcbTipoClienteActionPerformed

    private void resetFields()
    {    
        jtfId.setText("");
        jtfRazonSocial.setText("");
        jtfCuil.setText("");
        jtfNombre.setText(""); 
    }
    
    private void refreshTable()
    {
        try 
        {
            jtListadoCliente.setModel(new GrillaCliente(clienteControlador.listar()));
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(AbmCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JComboBox<String> jcbTipoCliente;
    private javax.swing.JLabel jlCuil;
    private javax.swing.JLabel jlId;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlRazonSociial;
    private javax.swing.JLabel jlTipoCliente;
    private javax.swing.JTable jtListadoCliente;
    private javax.swing.JTextField jtfCuil;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfRazonSocial;
    // End of variables declaration//GEN-END:variables
}
