/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventasdao.ui.abm;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ventasdao.controladores.CategoriaControlador;
import ventasdao.controladores.FormaPagoControlador;
import ventasdao.objetos.FormaPago;
import ventasdao.ui.grilla.GrillaFormaPago;

/**
 *
 * @author Hugo Chanampe
 */
public class AbmFormaPago extends javax.swing.JInternalFrame {

    /**
     * Creates new form AbmCategoria
     */
    private FormaPago formaPago;
    private FormaPagoControlador formaPagoControlador;
    private GrillaFormaPago grillaFormaPago;
    
    public AbmFormaPago() {
        initComponents();
        
        formaPagoControlador = new FormaPagoControlador();
        ArrayList<FormaPago> formaPagos = new ArrayList<>();

        try {
            formaPagos = (ArrayList<FormaPago>) formaPagoControlador.listar();
        } catch (Exception e) {
            e.printStackTrace ();
        }

        grillaFormaPago = new GrillaFormaPago(formaPagos);
        jtListadoFormaPago.setModel(grillaFormaPago);
    }
    
    public void limpiarCampos(){
    
    jtfNombre.setText("");
    jtfDescripcion.setText("");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jtfDescripcion = new javax.swing.JTextField();
        jbAltaCategoria = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListadoFormaPago = new javax.swing.JTable();
        jbModificar = new javax.swing.JButton();
        jtfId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jbEliminar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Categorias");

        jLabel1.setText("Nombre");

        jLabel2.setText("Descripcion");

        jbAltaCategoria.setText("Agregar");
        jbAltaCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAltaCategoriaMouseClicked(evt);
            }
        });
        jbAltaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaCategoriaActionPerformed(evt);
            }
        });

        jtListadoFormaPago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtListadoFormaPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtListadoFormaPagoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtListadoFormaPago);

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jtfId.setEnabled(false);
        jtfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIdActionPerformed(evt);
            }
        });

        jLabel3.setText("Id");

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jbAltaCategoria)
                        .addGap(18, 18, 18)
                        .addComponent(jbModificar)
                        .addGap(18, 18, 18)
                        .addComponent(jbEliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfNombre)
                            .addComponent(jtfDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(jtfId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 203, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAltaCategoria)
                    .addComponent(jbModificar)
                    .addComponent(jbEliminar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtListadoFormaPagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListadoFormaPagoMouseClicked
        
       FormaPago categoria = grillaFormaPago.getFormaPagoFromRow(jtListadoFormaPago.getSelectedRow());
       
       jtfNombre.setText(categoria.getNombre());
       jtfDescripcion.setText(categoria.getDescripcion());
       jtfId.setText(categoria.getId().toString());
    }//GEN-LAST:event_jtListadoFormaPagoMouseClicked

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        try {
            // TODO add your handling code here:
            formaPago = new FormaPago();
            
            formaPago.setId( Integer.parseInt( jtfId.getText() ) );
            
            if(jtfNombre.getText().length() >= 3 || jtfDescripcion.getText().length() >= 3)
            {
                formaPago.setNombre(jtfNombre.getText() );
                formaPago.setDescripcion( jtfDescripcion.getText() );
            }
            else
            {           
                JOptionPane.showMessageDialog(null, "Asegurese de colocar mas de 3 caracteres para guardar");
            }
            
            formaPagoControlador.modificar(formaPago);
        } catch (Exception ex) {
            Logger.getLogger(AbmFormaPago.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            jtListadoFormaPago.setModel( new GrillaFormaPago( (ArrayList<FormaPago>) formaPagoControlador.listar()));
        } catch (Exception ex) {
            Logger.getLogger(AbmFormaPago.class.getName()).log(Level.SEVERE, null, ex);
        }
        resetFields();
        refreshTable();
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jtfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIdActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        formaPago=new FormaPago();
        
        formaPago.setId( Integer.parseInt( jtfId.getText() ) );
        
        try {
            formaPagoControlador.eliminar(formaPago);
        } catch (Exception ex) {
            Logger.getLogger(AbmFormaPago.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            jtListadoFormaPago.setModel( new GrillaFormaPago( (ArrayList<FormaPago>) formaPagoControlador.listar()));
        } catch (Exception ex) {
            Logger.getLogger(AbmFormaPago.class.getName()).log(Level.SEVERE, null, ex);
        }
        resetFields();
        refreshTable();
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbAltaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaCategoriaActionPerformed

        // TODO add your handling code here:
        formaPago = new FormaPago();

        if(jtfNombre.getText().length() >= 3 || jtfDescripcion.getText().length() >= 3)
        {
            formaPago.setNombre(jtfNombre.getText());
            formaPago.setDescripcion(jtfDescripcion.getText());
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Asegurese de colocar mas de 3 caracteres para guardar");
        }
        
        //formaPago.setNombre(jtfNombre.getText());

        try {
            formaPagoControlador.crear(formaPago);
        } catch (Exception ex) {
            Logger.getLogger(AbmFormaPago.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            jtListadoFormaPago.setModel(new GrillaFormaPago((ArrayList<FormaPago>) formaPagoControlador.listar()));
        } catch (Exception ex) {
            Logger.getLogger(AbmFormaPago.class.getName()).log(Level.SEVERE, null, ex);
        }
        resetFields();
        refreshTable();
    }//GEN-LAST:event_jbAltaCategoriaActionPerformed

    private void jbAltaCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAltaCategoriaMouseClicked

    }//GEN-LAST:event_jbAltaCategoriaMouseClicked

    private void resetFields()
    {    
        jtfId.setText("");
        jtfNombre.setText("");
        jtfDescripcion.setText("");
    }
    
    private void refreshTable()
    {
        try 
        {
            jtListadoFormaPago.setModel(new GrillaFormaPago((ArrayList<FormaPago>) formaPagoControlador.listar()));
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(AbmFormaPago.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAltaCategoria;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JTable jtListadoFormaPago;
    private javax.swing.JTextField jtfDescripcion;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
}
