/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventasdao.ui.abm;

import com.sun.security.ntlm.Client;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import ventasdao.controladores.TipoClienteControlador;
import ventasdao.objetos.TipoCliente;
import ventasdao.ui.grilla.GrillaTipoCliente;

/**
 *
 * @author Hugo Chanampe
 */
public class AbmTipoCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form AbmCliente
     */
    private TipoCliente tipoCliente;
    private GrillaTipoCliente grillaTipoCliente;
    private TipoClienteControlador tipoClienteControlador = new TipoClienteControlador();
    
    
    
    public AbmTipoCliente() {
        initComponents();
        
        ArrayList<TipoCliente> clientes;
        try {
            clientes = (ArrayList<TipoCliente>) tipoClienteControlador.listar();
            grillaTipoCliente = new GrillaTipoCliente(clientes);
        } catch (Exception e) {
            e.printStackTrace ();
        }


        
        jtListadoTipoCliente.setModel(grillaTipoCliente);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfNombre = new javax.swing.JTextField();
        jtfDescripcion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListadoTipoCliente = new javax.swing.JTable();
        jbModificar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jtfId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);

        jLabel1.setText("Nombre");

        jLabel2.setText("Descrpcion");

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        jtListadoTipoCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtListadoTipoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtListadoTipoClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtListadoTipoCliente);

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jtfId.setEnabled(false);

        jLabel5.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfDescripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfId, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jbAgregar)
                .addGap(51, 51, 51)
                .addComponent(jbModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jbEliminar)
                .addGap(446, 446, 446))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregar)
                    .addComponent(jbModificar)
                    .addComponent(jbEliminar))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        // TODO add your handling code here:
        tipoCliente = new TipoCliente();
        
        tipoCliente.setNombre(jtfNombre.getText());
        tipoCliente.setDescripcion(jtfDescripcion.getText());
        
        try {
            tipoClienteControlador.crear(tipoCliente);
        } catch (Exception ex) {
            Logger.getLogger(AbmTipoCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            jtListadoTipoCliente.setModel(new GrillaTipoCliente((ArrayList<TipoCliente>)tipoClienteControlador.listar()));
        } catch (Exception ex) {
            Logger.getLogger(AbmTipoCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jtListadoTipoClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListadoTipoClienteMouseClicked
        // TODO add your handling code here:
        TipoCliente tipoCliente = grillaTipoCliente.getClienteFromRow(jtListadoTipoCliente.getSelectedRow());
        
        jtfNombre.setText(tipoCliente.getNombre());
        jtfDescripcion.setText(tipoCliente.getDescripcion());
        jtfId.setText(tipoCliente.getId().toString());
    }//GEN-LAST:event_jtListadoTipoClienteMouseClicked

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        tipoCliente = new TipoCliente();
        
        tipoCliente.setId(Integer.parseInt(jtfId.getText()));
        
        try {
            tipoClienteControlador.eliminar(tipoCliente);
        } catch (Exception ex) {
            Logger.getLogger(AbmTipoCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            jtListadoTipoCliente.setModel(new GrillaTipoCliente((ArrayList<TipoCliente>) tipoClienteControlador.listar()));
        } catch (Exception ex) {
            Logger.getLogger(AbmTipoCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        // TODO add your handling code here:
        tipoCliente = new TipoCliente();
        
        tipoCliente.setNombre(jtfNombre.getText());
        tipoCliente.setDescripcion(jtfDescripcion.getText());
        tipoCliente.setId(Integer.parseInt(jtfId.getText()));
        
        try {
            tipoClienteControlador.modificar(tipoCliente);
        } catch (Exception ex) {
            Logger.getLogger(AbmTipoCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            jtListadoTipoCliente.setModel(new GrillaTipoCliente((ArrayList<TipoCliente>) tipoClienteControlador.listar()));
        } catch (Exception ex) {
            Logger.getLogger(AbmTipoCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JTable jtListadoTipoCliente;
    private javax.swing.JTextField jtfDescripcion;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
}
